FROM notconf AS notconf-install
ARG COMPOSE_PATH

COPY ${COMPOSE_PATH} /notconf

RUN YANG_MODULES_DIR=/notconf /install-yang-modules.sh

FROM notconf AS notconf
COPY --from=notconf-install /etc/sysrepo /etc/sysrepo
