ARG IMAGE_TAG=latest

FROM notconf:${IMAGE_TAG} AS notconf-install
ARG COMPOSE_PATH

COPY ${COMPOSE_PATH} /notconf

RUN YANG_MODULES_DIR=/notconf /install-yang-modules.sh

FROM notconf:${IMAGE_TAG} AS notconf
COPY --from=notconf-install /etc/sysrepo /etc/sysrepo
